/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'dashboard': RouteRecordInfo<'dashboard', '/', Record<never, never>, Record<never, never>>,
    'config.languages': RouteRecordInfo<'config.languages', '/config/languages', Record<never, never>, Record<never, never>>,
    'config.website-settings': RouteRecordInfo<'config.website-settings', '/config/website-settings', Record<never, never>, Record<never, never>>,
    'entities': RouteRecordInfo<'entities', '/entities/:entity', { entity: ParamValue<true> }, { entity: ParamValue<false> }>,
    'entities.details': RouteRecordInfo<'entities.details', '/entities/:entity/:slug', { entity: ParamValue<true>, slug: ParamValue<true> }, { entity: ParamValue<false>, slug: ParamValue<false> }>,
    'entities.content': RouteRecordInfo<'entities.content', '/entities/:entity/:slug/content/:field', { entity: ParamValue<true>, slug: ParamValue<true>, field: ParamValue<true> }, { entity: ParamValue<false>, slug: ParamValue<false>, field: ParamValue<false> }>,
    'entities.media': RouteRecordInfo<'entities.media', '/entities/:entity/:slug/media', { entity: ParamValue<true>, slug: ParamValue<true> }, { entity: ParamValue<false>, slug: ParamValue<false> }>,
    'entities.index': RouteRecordInfo<'entities.index', '/entities/:entity', { entity: ParamValue<true> }, { entity: ParamValue<false> }>,
    'login': RouteRecordInfo<'login', '/login/:redirect?/:params?', { redirect?: ParamValueZeroOrOne<true>, params?: ParamValueZeroOrOne<true> }, { redirect?: ParamValueZeroOrOne<false>, params?: ParamValueZeroOrOne<false> }>,
  }
}
